// @generated by protoc-gen-connect-es v1.4.0
// @generated from file app.proto (package app, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateAppReply, CreateAppRequest, DeleteAppReply, DeleteAppRequest, FindAppByIDReply, FindAppByIDRequest, ListAppReply, ListAppRequest } from "./app_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service app.AppService
 */
export declare const AppService: {
  readonly typeName: "app.AppService",
  readonly methods: {
    /**
     * @generated from rpc app.AppService.CreateApp
     */
    readonly createApp: {
      readonly name: "CreateApp",
      readonly I: typeof CreateAppRequest,
      readonly O: typeof CreateAppReply,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc app.AppService.ListApp
     */
    readonly listApp: {
      readonly name: "ListApp",
      readonly I: typeof ListAppRequest,
      readonly O: typeof ListAppReply,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc app.AppService.FindAppByID
     */
    readonly findAppByID: {
      readonly name: "FindAppByID",
      readonly I: typeof FindAppByIDRequest,
      readonly O: typeof FindAppByIDReply,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc app.AppService.DeleteApp
     */
    readonly deleteApp: {
      readonly name: "DeleteApp",
      readonly I: typeof DeleteAppRequest,
      readonly O: typeof DeleteAppReply,
      readonly kind: MethodKind.Unary,
    },
  }
};

