// @generated by protoc-gen-es v1.9.0
// @generated from file app.proto (package app, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message app.AppDTO
 */
export declare class AppDTO extends Message<AppDTO> {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  constructor(data?: PartialMessage<AppDTO>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "app.AppDTO";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AppDTO;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AppDTO;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AppDTO;

  static equals(a: AppDTO | PlainMessage<AppDTO> | undefined, b: AppDTO | PlainMessage<AppDTO> | undefined): boolean;
}

/**
 * @generated from message app.CreateAppRequest
 */
export declare class CreateAppRequest extends Message<CreateAppRequest> {
  /**
   * @generated from field: app.AppDTO app = 1;
   */
  app?: AppDTO;

  constructor(data?: PartialMessage<CreateAppRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "app.CreateAppRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateAppRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateAppRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateAppRequest;

  static equals(a: CreateAppRequest | PlainMessage<CreateAppRequest> | undefined, b: CreateAppRequest | PlainMessage<CreateAppRequest> | undefined): boolean;
}

/**
 * @generated from message app.CreateAppReply
 */
export declare class CreateAppReply extends Message<CreateAppReply> {
  /**
   * @generated from field: app.AppDTO app = 1;
   */
  app?: AppDTO;

  constructor(data?: PartialMessage<CreateAppReply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "app.CreateAppReply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateAppReply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateAppReply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateAppReply;

  static equals(a: CreateAppReply | PlainMessage<CreateAppReply> | undefined, b: CreateAppReply | PlainMessage<CreateAppReply> | undefined): boolean;
}

/**
 * @generated from message app.ListAppRequest
 */
export declare class ListAppRequest extends Message<ListAppRequest> {
  /**
   * @generated from field: int32 app_id = 1;
   */
  appId: number;

  /**
   * @generated from field: int32 offset = 2;
   */
  offset: number;

  /**
   * @generated from field: int32 size = 3;
   */
  size: number;

  constructor(data?: PartialMessage<ListAppRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "app.ListAppRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListAppRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListAppRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListAppRequest;

  static equals(a: ListAppRequest | PlainMessage<ListAppRequest> | undefined, b: ListAppRequest | PlainMessage<ListAppRequest> | undefined): boolean;
}

/**
 * @generated from message app.ListAppReply
 */
export declare class ListAppReply extends Message<ListAppReply> {
  /**
   * @generated from field: repeated app.AppDTO apps = 1;
   */
  apps: AppDTO[];

  /**
   * @generated from field: int32 total = 2;
   */
  total: number;

  constructor(data?: PartialMessage<ListAppReply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "app.ListAppReply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListAppReply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListAppReply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListAppReply;

  static equals(a: ListAppReply | PlainMessage<ListAppReply> | undefined, b: ListAppReply | PlainMessage<ListAppReply> | undefined): boolean;
}

/**
 * @generated from message app.FindAppByIDRequest
 */
export declare class FindAppByIDRequest extends Message<FindAppByIDRequest> {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  constructor(data?: PartialMessage<FindAppByIDRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "app.FindAppByIDRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FindAppByIDRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FindAppByIDRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FindAppByIDRequest;

  static equals(a: FindAppByIDRequest | PlainMessage<FindAppByIDRequest> | undefined, b: FindAppByIDRequest | PlainMessage<FindAppByIDRequest> | undefined): boolean;
}

/**
 * @generated from message app.FindAppByIDReply
 */
export declare class FindAppByIDReply extends Message<FindAppByIDReply> {
  /**
   * @generated from field: app.AppDTO app = 1;
   */
  app?: AppDTO;

  constructor(data?: PartialMessage<FindAppByIDReply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "app.FindAppByIDReply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FindAppByIDReply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FindAppByIDReply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FindAppByIDReply;

  static equals(a: FindAppByIDReply | PlainMessage<FindAppByIDReply> | undefined, b: FindAppByIDReply | PlainMessage<FindAppByIDReply> | undefined): boolean;
}

/**
 * @generated from message app.DeleteAppRequest
 */
export declare class DeleteAppRequest extends Message<DeleteAppRequest> {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  constructor(data?: PartialMessage<DeleteAppRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "app.DeleteAppRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteAppRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteAppRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteAppRequest;

  static equals(a: DeleteAppRequest | PlainMessage<DeleteAppRequest> | undefined, b: DeleteAppRequest | PlainMessage<DeleteAppRequest> | undefined): boolean;
}

/**
 * @generated from message app.DeleteAppReply
 */
export declare class DeleteAppReply extends Message<DeleteAppReply> {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  constructor(data?: PartialMessage<DeleteAppReply>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "app.DeleteAppReply";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteAppReply;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteAppReply;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteAppReply;

  static equals(a: DeleteAppReply | PlainMessage<DeleteAppReply> | undefined, b: DeleteAppReply | PlainMessage<DeleteAppReply> | undefined): boolean;
}

