// @generated by protoc-gen-connect-es v1.4.0
// @generated from file app.proto (package app, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateAppReply, CreateAppRequest, DeleteAppReply, DeleteAppRequest, FindAppByIDReply, FindAppByIDRequest, ListAppReply, ListAppRequest } from "./app_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service app.AppService
 */
export const AppService = {
  typeName: "app.AppService",
  methods: {
    /**
     * @generated from rpc app.AppService.CreateApp
     */
    createApp: {
      name: "CreateApp",
      I: CreateAppRequest,
      O: CreateAppReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc app.AppService.ListApp
     */
    listApp: {
      name: "ListApp",
      I: ListAppRequest,
      O: ListAppReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc app.AppService.FindAppByID
     */
    findAppByID: {
      name: "FindAppByID",
      I: FindAppByIDRequest,
      O: FindAppByIDReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc app.AppService.DeleteApp
     */
    deleteApp: {
      name: "DeleteApp",
      I: DeleteAppRequest,
      O: DeleteAppReply,
      kind: MethodKind.Unary,
    },
  }
};

