// @generated by protoc-gen-es v1.9.0
// @generated from file app.proto (package app, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message app.AppDTO
 */
export const AppDTO = /*@__PURE__*/ proto3.makeMessageType(
  "app.AppDTO",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message app.CreateAppRequest
 */
export const CreateAppRequest = /*@__PURE__*/ proto3.makeMessageType(
  "app.CreateAppRequest",
  () => [
    { no: 1, name: "app", kind: "message", T: AppDTO },
  ],
);

/**
 * @generated from message app.CreateAppReply
 */
export const CreateAppReply = /*@__PURE__*/ proto3.makeMessageType(
  "app.CreateAppReply",
  () => [
    { no: 1, name: "app", kind: "message", T: AppDTO },
  ],
);

/**
 * @generated from message app.ListAppRequest
 */
export const ListAppRequest = /*@__PURE__*/ proto3.makeMessageType(
  "app.ListAppRequest",
  () => [
    { no: 1, name: "app_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "offset", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message app.ListAppReply
 */
export const ListAppReply = /*@__PURE__*/ proto3.makeMessageType(
  "app.ListAppReply",
  () => [
    { no: 1, name: "apps", kind: "message", T: AppDTO, repeated: true },
    { no: 2, name: "total", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message app.FindAppByIDRequest
 */
export const FindAppByIDRequest = /*@__PURE__*/ proto3.makeMessageType(
  "app.FindAppByIDRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message app.FindAppByIDReply
 */
export const FindAppByIDReply = /*@__PURE__*/ proto3.makeMessageType(
  "app.FindAppByIDReply",
  () => [
    { no: 1, name: "app", kind: "message", T: AppDTO },
  ],
);

/**
 * @generated from message app.DeleteAppRequest
 */
export const DeleteAppRequest = /*@__PURE__*/ proto3.makeMessageType(
  "app.DeleteAppRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message app.DeleteAppReply
 */
export const DeleteAppReply = /*@__PURE__*/ proto3.makeMessageType(
  "app.DeleteAppReply",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

