name: Build
on:
  push:
    branches:
      - "master"
      - "feat/ci"
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setupNode
        uses: actions/setup-node@v3
        with:
          node-version: "20.8"
      - name: setupDotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: GenTypeSpec
        run: |
          cd TypeSpec
          npm i
          npm run compile
          npm run gen
      - name: BuildDashboard
        run: |
          cd Dashboard
          dotnet build . --configuration Release
      - name: BuildDashboardWeb
        run: |
          cd Dashboard.Web
          npm i
          npm run build
      - name: BuildImageAndPushToDockerIO
        run: |
          cd Dashboard
          docker build . -t sheason/canarails:${{ github.sha }}
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker push sheason/canarails:${{ github.sha }}
